package demos.BookSearch;

/**
 * Generated by StMungo
 * Thu Mar 17 15:58:57 GMT 2022
 */
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class LMain {
    public static String safeRead(BufferedReader readerL) {
        String readline = "";
        try {
            readline = readerL.readLine();
        } catch(IOException e) {
            System.out.println("Input/Output error, unable to read");
            System.exit(-1);
        }
        return readline;
    }

    public static void main(String[] args) {
        // Create the current role
        LRole currentL =  new LRole();
        // readerL can be used to input strings, and then use them in send method invocation
        BufferedReader readerL = new BufferedReader(new InputStreamReader(System.in));
        // Method invocation follows the L typestate
        _Loop: do{
            switch(currentL.receive_LChoice1LabelFromU()) {
                case ADDBOOK:
                    Book payload1 = currentL.receive_addBookBookFromU();
                    System.out.println("Received from U: " + payload1);
                    break _Loop;
                case SKIPBOOK:
                    currentL.receive_skipBookFromU();
                    break _Loop;
            }
            switch(currentL.receive_LChoice2LabelFromU()) {
                case MOREBOOKS:
                    String payload4 = currentL.receive_moreBooksStringFromU();
                    System.out.println("Received from U: " + payload4);
                    continue _Loop;
                case END:
                    currentL.receive_endFromU();
                    break _Loop;
            }
        } while(true);
    }
}
